### ISSUE TITLE
Version 1.7 crashes on launch

### ISSUE THREAD

**Issue by bengreeno** [martinfekete10/Tuneful#121] opened 2024-10-29 18:09 UTC
After updating to the newest version (1.7) today, Tuneful seems to crash on launch. This is consistent every time I attempt to open Tuneful.

**Comment by martinfekete10** [comment] 2024-10-29 18:12
What version of macOS and what Mac are you using?

**Comment by bengreeno** [comment] 2024-10-29 18:14
￼

**Comment by bengreeno** [comment] 2024-10-29 18:56
Oh fun... the screenshot didn't come through. Here you go.
![CleanShot X 2024-10-29 12 14 14](https://github.com/user-attachments/assets/3c1bbc7e-99f4-4f9c-843e-b5bf3b66a7e9)

**Comment by martinfekete10** [comment] 2024-10-29 19:42
As I understand it, previous version works fine for you?

**Comment by bengreeno** [comment] 2024-10-29 19:46
Yes, I went back to the previous version when the new release didn't work. I have two Apple Silicon Macs running 15.1 and I updated Tuneful on both of them. Version 1.7 doesn't appear to work on either one.

**Comment by bengreeno** [comment] 2024-10-29 20:17
I'm going to try uninstalling Tuneful completely and reinstalling from scratch. We'll see what happens then.

**Comment by bengreeno** [comment] 2024-10-29 20:50
Uninstalled completely. Restarted machine and reinstalled Tuneful via GitHub. Crashes on launch. Crash log attached.
[Tuneful-2024-10-29-144641.txt](https://github.com/user-attachments/files/17562991/Tuneful-2024-10-29-144641.txt)

**Comment by nobodywasishere** [comment] 2024-10-30 14:29
I'm also running into the same issue. M3 Pro Macbook Pro.
[tuneful-crash-log-2024-10-30.txt](https://github.com/user-attachments/files/17574447/tuneful-crash-log-2024-10-30.txt)

**Comment by VisualisationExpo** [comment] 2024-10-31 09:08
[Tuneful-2024-10-31-100347.txt](https://github.com/user-attachments/files/17585491/Tuneful-2024-10-31-100347.txt)
Same

**Comment by aayushbhatia06** [comment] 2024-11-05 06:07
Same(ish) issue. If I install via GitHub, app crashes on launch. Installing via Homebrew everything works except any of the menu bar features (menu bar icon never shows up). Will share logs when home

**Comment by VisualisationExpo** [comment] 2024-11-05 07:07
I know this is for 1.7 but versions from 1.6.6 and up to 1.7 crashes on launch.. 1.6.6 and 1.6.7 - last good known release for me personally is 1.6.5. On Apple Silicon and Sequoia 15.1

report for 1.6.6
[Tuneful-2024-11-05-080006.txt](https://github.com/user-attachments/files/17628335/Tuneful-2024-11-05-080006.txt)

and 1.6.7 - perhaps there's something to be said of these crashes in relation to 1.7
[Tuneful-2024-11-05-075747.txt](https://github.com/user-attachments/files/17628347/Tuneful-2024-11-05-075747.txt)

**Comment by hymnalayanroots** [comment] 2024-11-05 11:23
Same for Macbook Air M3 macOS Sequoia 15.2 beta 2

**Comment by exiva** [comment] 2024-11-07 21:12
[Tuneful-2024-11-07-161020.txt](https://github.com/user-attachments/files/17669486/Tuneful-2024-11-07-161020.txt)
m2 mac mini crashlog

**Comment by stanislc** [comment] 2024-11-10 03:50
Same issue, M4 Mac mini. Log is attached.
[Tuneful-2024-11-09-224018.txt](https://github.com/user-attachments/files/17690092/Tuneful-2024-11-09-224018.txt)

**Comment by exiva** [comment] 2024-11-20 21:40
Installing spotify fixes the crash, app loads fine after. #129

**Comment by martinfekete10** [comment] 2024-11-21 09:13
Yep, this seems to be the root cause, thanks @exiva. Will try to fix the issue and release the new version in the upcoming days

**Comment by martinfekete10** [comment] 2024-11-23 18:17
I just release v1.7.1 which (hopefully) fixes this issue! If it works for you I'll close the issue

**Comment by bilalnoork** [comment] 2024-11-23 23:50
M1 Pro Sequoia 15.1.1, still broken for me. I use spicetify (hence my hesitancy to reinstall), wonder if that has anything to do with it

**Comment by det-box** [comment] 2024-11-25 10:07
Hello,
it is now working correctly for me.
Thank you.
Mac mini M1 with 15.1.1 and
MacBookPro M2 with 15.1.1

**Comment by bengreeno** [comment] 2024-11-25 21:47
> I just release v1.7.1 which (hopefully) fixes this issue! If it works for you I'll close the issue

@martinfekete10 Thanks for your work on this! The new version is working great!

**Closed** 2024-11-25 21:47 UTC
