### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Senajs** [martinfekete10/Tuneful#37] opened 2023-12-27 18:37 UTC
Hi,

after installing the app - and when i try to launch it - I get an error message" App cannot be started since apple cannot search within it for malicious code- the app needs to be updated"

MacOS Sonoma

KR
Šenaj

**Comment by martinfekete10** [comment] 2023-12-28 11:25
Hi, are you talking about [this issue](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac)? If yes, this is caused by the fact that I am not enrolled in Apple Developer Programme and app is not authorized by Apple. App can still be opened by righ-clicking on app icon in Finder -> Open (this needs to be done only once).

Closing this issue, if it still fails for you, feel free to re-open.

**Closed by martinfekete10** 2023-12-28 11:25 UTC
